#cloud-config

hostname: "coreos1"
ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZzrQD/FDCnNsTOKMRrvjZIhu+NVMeJuFiwA0YR1kCjLTvcSnroE2s+XEhaWonrZckA2Mt1ieHY+O2iWVqYFu7wwqMXlc6iJdBp4BmpjEmKJaXDb5s7SWZTWyUHseSHDQtP1MGPmGBDAms/mxhDw8OPnHA1wUt4FwnWUW4kBEBL3M0rPkXpxR6X84UdhCTvRihLHUFhSDhmqDJhPTBPuuR9GENhvSsopY0p/B+0ys5ym7U0qHQCwD8ctbf/soGPicHLYFhTDV2EnHI3wFpz9VoJ/4bOxuWDy1w2maY2Gu7S54E7jAxzXEULu//8TcfQCYYYRbnMqs28qP2CldTp+AL coreos"

users:
  - name: core
    passwd: "$6$rTZyy4jR$csRM9u.QjHFKv0DVJTBp.0lTtl7semjDvJ32L6ZiJ/eBbp8O8vRQe.ZNJTqsa3zqKWP82gu1Cdmp3Wn.H9vPm."
  - name: vilain
    passwd: "$6$rTZyy4jR$csRM9u.QjHFKv0DVJTBp.0lTtl7semjDvJ32L6ZiJ/eBbp8O8vRQe.ZNJTqsa3zqKWP82gu1Cdmp3Wn.H9vPm."
    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZzrQD/FDCnNsTOKMRrvjZIhu+NVMeJuFiwA0YR1kCjLTvcSnroE2s+XEhaWonrZckA2Mt1ieHY+O2iWVqYFu7wwqMXlc6iJdBp4BmpjEmKJaXDb5s7SWZTWyUHseSHDQtP1MGPmGBDAms/mxhDw8OPnHA1wUt4FwnWUW4kBEBL3M0rPkXpxR6X84UdhCTvRihLHUFhSDhmqDJhPTBPuuR9GENhvSsopY0p/B+0ys5ym7U0qHQCwD8ctbf/soGPicHLYFhTDV2EnHI3wFpz9VoJ/4bOxuWDy1w2maY2Gu7S54E7jAxzXEULu//8TcfQCYYYRbnMqs28qP2CldTp+AL coreos"
    groups: [ sudo, docker ]

write_files: 
  - path: /etc/sudoers.d/vilain
    owner: root
    permissions: "0600"
    content: "vilain ALL=(ALL) NOPASSWD: ALL"

coreos:
  units:
    - name: 00-ens32.network
      enable: true
      content: |
        [Match]
        Name=ens32
      
        [Network]
        DNS=8.8.8.8 8.8.6.6
        Address=192.168.1.224/24
        Gateway=192.168.1.254

    - name: format-var-lib-docker.service
      content: |
        [Unit]
        Before=docker.service var-lib-docker.mount
        RequiresMountsFor=/var/lib
        ConditionPathExists=!/var/lib/docker

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=-/sbin/parted -s /dev/sdb mklabel gpt
        ExecStart=-/sbin/parted -s /dev/sdb mkpart ext4 0 85%
        ExecStart=-/usr/sbin/mkfs.ext4 /dev/sdb1

    - name: var-lib-docker.mount
      enable: true
      command: start
      content: |
        [Unit]
        Before=docker.service
        After=format-var-lib-docker.service
        Requires=format-var-lib-docker.service

        [Mount]
        What=/dev/sdb1
        Where=/var/lib/docker
        Type=ext4
        Options=defaults
        #Options=loop,discard
        [Install]
        RequiredBy=docker.service

    - name: docker.service
      enable: true
      command: start
      drop-ins:
        - name: 10-wait-docker.conf
          content: |
            [Unit]
            After=var-lib-docker.mount
            Requires=var-lib-docker.mount
