---

- hosts: master
  become: true
  tasks:

#################################################################
#  setup a new kubernetes master or worker node

  - assert:
      that:
        - node_ip is defined
      msg: node_ip must be defined in calling this playbook

  - name: COM.1-Update apt-get repo and cache
    apt: 
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600
    register: mas_com_1
  - debug: var=mas_com_1

  - name: COM.2-Install packages that allow installs over HTTPS
    package:
      name: "{{ packages }}"
      state: present
      update_cache: no
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    register: mas_com_2
#  - debug: var=mas_com_2.stdout_lines

  - name: COM.3-Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    register: mas_com_3
#  - debug: var=mas_com_3.stdout_lines

  - name: COM.4-Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
    register: mas_com_4
#  - debug: var=mas_com_4.stdout_lines

  - name: COM.5-Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status
    register: mas_com_5
  - debug: var=mas_com_5.stdout_lines

  # https://github.com/kubernetes/kubeadm/issues/1394
  - name: COM.6-set docker to use systemd driver
    copy: 
      dest: /etc/docker/daemon.json
      content: |
        # THIS FILE IS CONTROLLED BY ANSIBLE - DO NOT CHANGE IN DEPLOYMENT!
        # Setup daemon.
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2"
        }
      owner: root
      group: root
      mode: "0644"
    notify:
      - docker status
    register: mas_com_6
#  - debug: var=mas_com_6

  - name: COM.7-Add vagrant user to docker group
    user:
      name: vagrant
      group: docker
    register: mas_com_7
#  - debug: var=mas_com_7.stdout_lines

  - name: COM.8-Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
    register: mas_com_8
#  - debug: var=mas_com_8.stdout_lines

  - name: COM.9-Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0
    register: mas_com_9
#  - debug: var=mas_com_9.stdout_lines

  - name: COM.10-Create calico nodename for node stats
    file:
      name: "{{ item }}"
      state: directory
      recurse: yes
      owner: root
      group: root
    register: mas_com_10
    with_items:
      - /var/lib/calico
#  - debug: var=mas_com_10

  - name: COM.11-Create calico nodename for node stats
    file:
      name: /var/lib/calico/nodename
      state: touch
      owner: root
      group: root
    register: com_11
#  - debug: var=com_11

#################################################################

  - name: MAS.1-Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: MAS.2-Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: MAS.3-Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl
    register: mas_3
  - debug: var=mas_3.stdout_lines

  - name: MAS.4-setup kubelet for extra args
    file:
      path: /etc/default/kubelet
      owner: root
      group: root
      state: touch

  # node_ip passed on the command line
  - name: MAS.5-Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip="{{ node_ip }}"

  - name: MAS.6-Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: MAS.7-Initialize the Kubernetes cluster using kubeadm (this will take a while)
    command: kubeadm init 
        --apiserver-advertise-address="192.168.50.10" 
        --apiserver-cert-extra-sans="192.168.50.10"  
        --node-name k8s-master 
        --pod-network-cidr=192.168.0.0/16
    args:
      creates: /etc/kubernetes/manifests/kube-apiserver.yaml
    register: mas_7
  - debug: var=mas_7.stdout_lines

  - name: MAS.8-setup .kube/ for vagrant user
    file:
      path: /home/vagrant/.kube
      state: directory
      recurse: yes
      owner: vagrant
      group: vagrant

  - name: MAS.9-copy admin.conf to .kube/config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      remote_src: yes
      owner: vagrant
      group: vagrant

  - name: MAS.10-copy certs to local repo
    fetch:
      src: "/etc/kubernetes/pki/{{ item }}"
      dest: "{{ item }}"
      flat: yes
    with_items:
      - ca.crt
      - apiserver-kubelet-client.crt
      - apiserver-kubelet-client.key

  # https://docs.projectcalico.org/getting-started/kubernetes/quickstart
  - name: MAS.11-Install calico pod network
    become: false
    command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
    register: mas_11
  - debug: var=mas_11.stdout_lines

  # https://github.com/kubernetes/dashboard#kubernetes-dashboard
  # uses apply so it can be run idempotently
#  - name: MAS.12-installing dashboard add-on
#    become: false
#    command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc6/aio/deploy/recommended.yaml
#    register: mas_12
#  - debug: var=mas_12.stdout_lines

  - name: MAS.13-Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: MAS.14-Copy join command to local file
    local_action: copy 
      content="{{ join_command.stdout_lines[0] }}"
      dest="./join-command"


  handlers:
  - name: docker status
    service: name=docker state=started
