---
- hosts: all
  become: true
  tasks:

#################################################################
#  setup a new kubernetes master or worker node

  - name: COM.1-Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: COM.2-Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: COM.3-Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: COM.4-Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  - name: COM.5-Add vagrant user to docker group
    user:
      name: vagrant
      group: docker


  - name: COM.6-Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: COM.7-Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

#################################################################

# master node creates join command here
#
  - name: NODE.1-Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: NODE.2-Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: NODE.3-Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubeadm 
        - kubectl

  - name: NODE.4-Copy the join command to server location
    copy: 
      src: join-command 
      dest: /tmp/join-command.sh 
      mode: 0777

  - name: NOD.5-Join the node to cluster
    command: sh /tmp/join-command.sh

  handlers:
  - name: docker status
    service: name=docker state=started
