Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.33.9"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"

    file_to_disk = File.realpath( "." ).to_s + "/disk.vdi"

    if ARGV[0] == "up" && ! File.exist?(file_to_disk)
       vb.customize [
            'createmedium', 'disk',
            '--filename', file_to_disk,
            '--format', 'VMDK',
            '--size', 30 * 1024, # 30 GB
            '--variant', 'Standard'
            ]
       vb.customize [
            'storageattach', :id,
            '--storagectl', 'SATA Controller', # The name may vary
            '--port', 1, 
            '--device', 0,
            '--type', 'hdd', 
            '--medium', file_to_disk
            ]
    end
  end

  # Two partition in one disk
  config.vm.provision "shell", inline: <<-SHELL
set -e
set -x

if [ -f /etc/provision_env_disk_added_date ]
then
   echo "Provision runtime already done."
   exit 0
fi


sudo fdisk -u /dev/sdb <<EOF
n
p
1

+500M
n
p
2


w
EOF

mkfs.ext4 /dev/sdb1
mkfs.ext4 /dev/sdb2
mkdir -p /{datadir,extra}
mount -t ext4 /dev/sdb1 /datadir
mount -t ext4 /dev/sdb2 /extra

date > /etc/provision_env_disk_added_date
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    echo "provision complete"
  SHELL
end