file_root = File.dirname(File.expand_path(__FILE__))
file_to_disk = File.realpath( file_root ).to_s + "/disk.vmdk"

Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.16.4"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"



    if ARGV[0] == "up" && ! File.exist?(file_to_disk)
      vb.customize [
      'createmedium', 'disk',
      '--filename', file_to_disk,
      '--format', 'VMDK',
      '--size', 30 * 1024, # 30 GB
      '--variant', 'Standard'
      ]
      vb.customize [
      'storageattach', :id,
      '--storagectl', 'SATA Controller', # The name may vary
      '--port', 1, 
      '--device', 0,
      '--type', 'hdd', 
      '--medium', file_to_disk
      ]
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
set -e
set -x

if [ -f /etc/provision_env_disk_added_date ]
then
   echo "Provision runtime already done."
   exit 0
fi

sudo parted -s /dev/sdb mklabel gpt
sudo parted -s /dev/sdb mkpart ext3 0 100%

mkfs.ext4 /dev/sdb1
mkdir -p /datadir
mount -t ext4 /dev/sdb1 /datadir
echo "/dev/sdb1 /datadir ext4 defaults 0 0" >> /etc/fstab
date > /etc/provision_env_disk_added_date
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    echo "provision complete"
  SHELL
end